import craftVocabularyData from "./data/craft-vocabulary.json";

/** Contextual word pools — influenced by batch properties. */
export const CONTEXT_WORDS = {
  early: [
    "Early",
    "Bright Start",
    "First Light",
    "Sunrise",
    "Daybreak",
    "Dawn Patrol",
    "Before Breakfast",
    "Early Bird",
    "Morning Glow",
    "First Shift",
    "Up With the Sun",
    "Fresh Beginning",
    "New Day",
    "Dawn Blend",
    "Early Rising",
    "Before Coffee",
    "First Thing",
    "Opening Hour",
    "Crack of Dawn",
    "Bright and Early",
    "Quiet Dawn",
    "Wake-Up Pour",
    "Sunrise Special",
    "Morning Spark",
    "First One In",
  ],

  morning: [
    "Morning",
    "Fresh Start",
    "Daybreak",
    "First Pour",
    "Morning Momentum",
    "Morning Measure",
    "Freshly Started",
    "Coffee Time",
    "Breakfast Batch",
    "Morning Shift",
    "Bright Morning",
    "New Day Blend",
    "Morning Craft",
    "Rise and Mix",
    "Morning Glory",
    "Fresh Energy",
    "Day Starter",
    "Early Progress",
    "Morning Standard",
    "Sunlit Pour",
    "Ready for the Day",
    "Morning Edition",
    "First Cup",
    "Daily Opener",
    "Morning Run",
  ],

  midday: [
    "Midday",
    "Lunch Break",
    "Noon",
    "Halfway There",
    "High Noon",
    "Midday Measure",
    "Lunch Hour",
    "Noon Shift",
    "Daylight Blend",
    "Midday Momentum",
    "Half-Day Pour",
    "Center of the Day",
    "Noontime",
    "Lunch Special",
    "Midday Craft",
    "Day in Progress",
    "Noon Reserve",
    "Middle Shift",
    "Peak Daylight",
    "Halfway Home",
    "Midday Edition",
    "Noon Batch",
    "Daytime Mix",
    "Lunch Is Waiting",
    "Second Coffee",
  ],

  afternoon: [
    "Afternoon",
    "Steady",
    "Day Shift",
    "Second Wind",
    "Afternoon Flow",
    "Late Lunch",
    "Steady Progress",
    "Afternoon Craft",
    "Daylight Pour",
    "Second Half",
    "Post-Lunch",
    "Afternoon Reserve",
    "Day in Motion",
    "Working Hours",
    "Still Going",
    "Afternoon Momentum",
    "Mid-Shift",
    "Golden Afternoon",
    "Daylight Blend",
    "Steady Hands",
    "Afternoon Edition",
    "Back to Work",
    "Full Swing",
    "Productive Hour",
    "Almost Evening",
  ],

  evening: [
    "Evening",
    "Sunset",
    "Last Light",
    "Home Stretch",
    "Evening Glow",
    "Golden Hour",
    "Closing Shift",
    "Sunset Pour",
    "Evening Reserve",
    "Day's End",
    "Almost Home",
    "Last Round",
    "Final Hours",
    "Evening Craft",
    "Twilight",
    "Dusk Blend",
    "End of Day",
    "Late Edition",
    "Closing Time",
    "Sunset Special",
    "Final Push",
    "Evening Measure",
    "After Work",
    "Last Call",
    "One More Before Home",
  ],

  night: [
    "Night Owl",
    "Late Shift",
    "Moonlight",
    "After Hours",
    "Midnight",
    "Night Shift",
    "Moonlit",
    "Past Bedtime",
    "Dark Hour",
    "Midnight Mix",
    "Late-Night Pour",
    "Quiet Night",
    "Night Reserve",
    "After Dark",
    "Sleepless Blend",
    "Night Watch",
    "Moonrise",
    "Last One Standing",
    "Working Late",
    "Night Edition",
    "Midnight Measure",
    "Lights Still On",
    "Overtime",
    "Late but Great",
    "Tomorrow's Problem",
  ],

  tiny: [
    "Tiny",
    "Mini",
    "Little",
    "Pocket",
    "Micro",
    "Petite",
    "Compact",
    "Small Wonder",
    "Tiny Titan",
    "Miniature",
    "Lightweight",
    "Small but Mighty",
    "Little Legend",
    "Pocket-Sized",
    "Quick",
    "Bite-Sized",
    "Junior",
    "Small Scale",
    "Tiny Treasure",
    "Minimal",
    "Featherweight",
    "Little One",
    "Short Pour",
    "Mini Reserve",
    "Small Fry",
  ],

  small: [
    "Small",
    "Compact",
    "Light",
    "Quick",
    "Modest",
    "Easy",
    "Handy",
    "Neat",
    "Lean",
    "Light Touch",
    "Quick Pour",
    "Small Batch",
    "Compact Craft",
    "Easy Measure",
    "Simple",
    "Trim",
    "Short Run",
    "Light Work",
    "Small Scale",
    "Low-Key",
    "Little Extra",
    "Convenient",
    "Practical",
    "Everyday",
    "Just Enough",
  ],

  medium: [
    "Balanced",
    "Classic",
    "Steady",
    "Standard",
    "Regular",
    "Everyday",
    "Reliable",
    "Middle Ground",
    "Just Right",
    "Measured",
    "Well Balanced",
    "House Standard",
    "Traditional",
    "Familiar",
    "Comfortable",
    "Dependable",
    "Even",
    "Moderate",
    "Core",
    "Mainstay",
    "Daily",
    "Go-To",
    "Trusted",
    "Smooth",
    "Ordinary Excellence",
  ],

  large: [
    "Big",
    "Mighty",
    "Heavy",
    "Grand",
    "Bold",
    "Substantial",
    "Powerful",
    "Strong",
    "Generous",
    "Big League",
    "Heavy Duty",
    "Large Scale",
    "Full Strength",
    "Serious",
    "Major",
    "Robust",
    "Commanding",
    "Big Pour",
    "Main Event",
    "Heavyweight",
    "Power Batch",
    "Extra Large",
    "Strong Measure",
    "Big Energy",
    "Workhorse",
  ],

  huge: [
    "Giant",
    "Massive",
    "Titan",
    "Monumental",
    "Colossal",
    "Enormous",
    "Mega",
    "Supersized",
    "Maximum",
    "Mammoth",
    "Heavy Hitter",
    "Grand Scale",
    "Biggest One",
    "Oversized",
    "Epic",
    "Industrial",
    "Towering",
    "Full Power",
    "King Size",
    "Maximum Effort",
    "Absolute Unit",
    "Bucket Buster",
    "The Big One",
    "Major League",
    "No Small Matter",
  ],

  lightFill: [
    "Light Pour",
    "Easy Fill",
    "Open Bucket",
    "Room to Spare",
    "Plenty of Space",
    "Light Load",
    "Low Fill",
    "Easy Measure",
    "Barely Started",
    "First Layer",
    "Bottom of the Bucket",
    "Plenty of Headroom",
    "Gentle Fill",
    "Open Top",
    "Lightly Loaded",
    "Easy Going",
    "Short Pour",
    "Small Serving",
    "Just a Little",
    "Bucket Breathing Room",
    "Space Available",
    "Low Tide",
    "First Scoop",
    "Starter Fill",
    "Modest Measure",
  ],

  quarterFill: [
    "Quarter Measure",
    "Quarter Full",
    "One Part Full",
    "First Quarter",
    "Light Quarter",
    "Roomy Pour",
    "A Little Something",
    "Just Getting Started",
    "Early Fill",
    "Bottom Quarter",
    "Small Portion",
    "Quarter Batch",
    "First Stage",
    "Easy Quarter",
    "Low-Level Pour",
    "Plenty Left",
    "Mostly Empty",
    "One Quarter Wonder",
    "Beginning Fill",
    "Starter Portion",
  ],

  halfFill: [
    "Half Measure",
    "Middle Ground",
    "Halfway Mix",
    "Half Full",
    "Halfway There",
    "Balanced Fill",
    "Middle Measure",
    "Half Bucket",
    "Perfectly Half",
    "Center Fill",
    "Equal Space",
    "Mid-Level",
    "Half and Happy",
    "Fifty-Fifty",
    "Middle Pour",
    "Halfway Home",
    "The Middle One",
    "Balanced Bucket",
    "Half Load",
    "Right in the Middle",
    "Halfway Special",
    "Midpoint Mix",
    "The Optimist",
    "Half Full Energy",
    "Split Measure",
  ],

  threeQuarterFill: [
    "Three-Quarter Measure",
    "Three Quarters Full",
    "Getting Full",
    "Nearly There",
    "Closing In",
    "Comfortably Full",
    "Upper Measure",
    "Mostly Full",
    "Room for a Little More",
    "Three-Quarter Pour",
    "Almost Topped",
    "Upper Fill",
    "Well Filled",
    "Just Below Full",
    "Final Quarter",
    "Nearly Packed",
    "More Full Than Empty",
    "High Tide",
    "Strong Fill",
    "Top Quarter",
  ],

  nearlyFull: [
    "Nearly Full",
    "Top Up",
    "Almost Brimming",
    "Close to Full",
    "Almost Topped",
    "Near the Rim",
    "Just About Full",
    "Tight Fit",
    "Room for One More",
    "High Fill",
    "Top Measure",
    "Close Call",
    "Almost Overflowing",
    "Packed In",
    "Nearly Maxed",
    "Full Enough",
    "One Step from Full",
    "At the Top",
    "Maximum Comfort",
    "Snug Fit",
    "Almost There",
    "Top Shelf",
    "Final Top-Up",
    "Edge of Full",
    "Barely Any Room",
  ],

  full: [
    "Full Measure",
    "Full Bucket",
    "Brimming",
    "Filled Up",
    "Filled to the Top",
    "Maximum Fill",
    "Top to Bottom",
    "No Room Left",
    "Perfectly Full",
    "Full Capacity",
    "Bucket Complete",
    "At the Limit",
    "Packed Full",
    "Top Level",
    "Full Send",
    "Maximum Measure",
    "Filled and Ready",
    "All the Way",
    "Top-Off",
    "Complete Fill",
    "Full Load",
    "Bucket Goals",
    "Big Bucket Energy",
    "Nothing More Fits",
    "Right to the Rim",
  ],

  overflow: [
    "Overflowing",
    "Over the Top",
    "Too Much of a Good Thing",
    "Beyond Full",
    "Bucket Buster",
    "Maximum Plus",
    "No More Room",
    "Overfilled",
    "Above the Line",
    "Extra Full",
    "More Than Enough",
    "Pushing the Limit",
    "Past Capacity",
    "Overflow Energy",
    "One Scoop Too Many",
  ],

  under: [
    "Easy Going",
    "Room to Spare",
    "Light Work",
    "Under Control",
    "Gentle Measure",
    "Below Target",
    "Taking It Easy",
    "Light Touch",
    "Modest Pour",
    "Keeping It Small",
    "Easy Does It",
    "Comfortably Under",
    "Plenty Left",
    "Less Is More",
    "Short Measure",
    "Soft Landing",
    "Under the Line",
    "Low-Key",
    "Simple Portion",
    "Lean Batch",
    "Safe and Small",
    "Quiet Measure",
    "No Rush",
    "Lightly Done",
    "Conservative Pour",
  ],

  close: [
    "Just Right",
    "Perfect Measure",
    "On Target",
    "Right on the Mark",
    "Perfect Fit",
    "Exactly Enough",
    "Nicely Balanced",
    "Target Acquired",
    "Precision Pour",
    "Sweet Spot",
    "Right Where It Should Be",
    "Measured Well",
    "Spot On",
    "Exact Match",
    "Perfectly Pitched",
    "Ideal Measure",
    "Balanced Result",
    "Right in Range",
    "Fine Measure",
    "On Point",
    "Near Perfect",
    "The Goldilocks Batch",
    "Accurate Enough",
    "Nailed It",
    "Bullseye",
  ],

  over: [
    "Heavy Hitter",
    "Big Pour",
    "Extra Measure",
    "Above Target",
    "Going Big",
    "A Little Extra",
    "Generous Measure",
    "Overachiever",
    "Heavy Hand",
    "Bonus Pour",
    "More Is More",
    "Extra Strength",
    "Beyond the Mark",
    "Oversized",
    "Big Ambition",
    "Loaded Up",
    "Full Power",
    "Extra Helping",
    "A Touch More",
    "Strong Pour",
    "Above and Beyond",
    "Maximum Effort",
    "Over the Line",
    "Big Plans",
    "No Half Measures",
  ],

  simpleRecipe: [
    "Simple",
    "Clean",
    "Pure",
    "Straightforward",
    "Classic",
    "Essential",
    "No-Nonsense",
    "Minimal",
    "Basic but Brilliant",
    "Simple Pleasure",
    "Clean Cut",
    "Direct",
    "Uncomplicated",
    "Pure and Simple",
    "Easy Formula",
    "Bare Essentials",
    "Simple Craft",
    "Classic Pairing",
    "Less Is More",
    "Straight Mix",
  ],

  standardRecipe: [
    "Balanced",
    "Crafted",
    "Well Rounded",
    "House",
    "Classic",
    "Traditional",
    "Trusted",
    "Signature",
    "Core",
    "Established",
    "Regular",
    "Reliable",
    "Familiar",
    "Proven",
    "Standard Craft",
    "House Favorite",
    "Everyday Reserve",
    "Steady Formula",
    "Classic Combination",
    "Well Built",
  ],

  complexRecipe: [
    "Complex",
    "Layered",
    "Intricate",
    "Grand",
    "Master",
    "Elaborate",
    "Detailed",
    "Sophisticated",
    "Fine Tuned",
    "Deep Blend",
    "Full Composition",
    "Many-Part Harmony",
    "Master Formula",
    "Grand Assembly",
    "Layered Reserve",
    "Complex Character",
    "Carefully Composed",
    "Richly Built",
    "Technical Masterpiece",
    "Advanced Blend",
  ],

  balancedRatio: [
    "Balanced",
    "In Harmony",
    "Evenly Matched",
    "Perfect Pairing",
    "Well Proportioned",
    "Smooth Balance",
    "Equal Standing",
    "Fine Harmony",
    "In Tune",
    "Nicely Blended",
    "Balanced Craft",
    "Even Measure",
    "Perfect Union",
    "Steady Composition",
    "Harmony Blend",
    "Right in Balance",
    "Equal Partners",
    "Balanced Reserve",
    "Well Matched",
    "Smoothly Divided",
  ],

  dominantRatio: [
    "Bold",
    "Forward",
    "Leading",
    "Strong",
    "Dominant",
    "Main Character",
    "Front and Center",
    "Heavy on the Good Stuff",
    "Clearly Defined",
    "Strongly Led",
    "Boldly Built",
    "Lead Ingredient",
    "Primary Pour",
    "Center Stage",
    "Strong Foundation",
    "Main Event",
    "Driven",
    "Full Character",
    "Richly Forward",
    "Leading Blend",
  ],

  firstBatch: [
    "First Batch",
    "Opening Pour",
    "First of the Day",
    "Batch One",
    "The Opener",
    "First Run",
    "Starting Line",
    "Opening Measure",
    "Fresh Beginning",
    "First Edition",
    "The Beginning",
    "Day One",
    "First in Line",
    "Opening Act",
    "First Craft",
    "Initial Pour",
    "The Starter",
    "First and Finest",
    "First Step",
    "Fresh Off the Mark",
  ],

  lastBatch: [
    "Final Batch",
    "Closing Pour",
    "Last One",
    "Grand Finale",
    "The Closer",
    "Final Measure",
    "Last Batch Standing",
    "End of the Line",
    "One for the Road",
    "Closing Act",
    "Final Edition",
    "That's a Wrap",
    "Last Call",
    "The Finish",
    "Done for the Day",
    "Final Craft",
    "One More and Done",
    "End Shift",
    "Closing Time",
    "The Last Pour",
  ],

  friday: [
    "Friday Finish",
    "Friday Pour",
    "Friday Feeling",
    "Friday Special",
    "Weekend Loading",
    "Friday Reserve",
    "Final Friday",
    "Friday Craft",
    "Weekend Warm-Up",
    "Friday Finale",
    "Almost Weekend",
    "Friday Freedom",
    "Last Push Friday",
    "Friday's Finest",
    "End-of-Week Blend",
    "Friday House Special",
    "Weekend Starter",
    "Friday Edition",
    "The Friday One",
    "Friday Done Right",
  ],

  weekend: [
    "Weekend Warrior",
    "Weekend Pour",
    "Weekend Special",
    "Saturday Craft",
    "Sunday Blend",
    "Weekend Reserve",
    "Off-Day Mix",
    "Weekend Edition",
    "Saturday Session",
    "Sunday Special",
    "Weekend Project",
    "Slow Day Pour",
    "Weekend Energy",
    "Day-Off Blend",
    "Saturday Standard",
    "Sunday Measure",
    "Weekend Workshop",
    "Leisure Mix",
    "Weekend Batch",
    "Easy Weekend",
  ],

  lateShift: [
    "Time to Go Home",
    "Home Stretch",
    "Closing Time",
    "One More Pour",
    "Last Batch Standing",
    "Still Working",
    "Almost Done",
    "End Shift",
    "Overtime",
    "One More and Done",
    "Lights Still On",
    "Final Push",
    "After-Hours Craft",
    "Last Call",
    "Clocking Out Soon",
    "The Long Day",
    "Past Closing",
    "Late Shift Special",
    "Home Is Calling",
    "Tomorrow Can Wait",
  ],

  precise: [
    "Exact",
    "Measured",
    "Precise",
    "Fine Tuned",
    "Perfectly Pitched",
    "Calculated",
    "On Point",
    "Dialed In",
    "Carefully Measured",
    "Exact Science",
    "Sharp Measure",
    "Precision Crafted",
    "Right on Target",
    "Fine Measure",
    "Technical",
    "Perfect Ratio",
    "Measured Twice",
    "Accurate",
    "Spot On",
    "Engineered",
  ],

  playful: [
    "Happy",
    "Cheeky",
    "Curious",
    "Lucky",
    "Unexpected",
    "Slightly Suspicious",
    "Probably Fine",
    "Mostly Intentional",
    "Good Enough",
    "Trust the Process",
    "A Little Different",
    "Boldly Questionable",
    "Casually Precise",
    "Optimistically Measured",
    "Surprisingly Good",
    "Not Bad",
    "Mildly Impressive",
    "Definitely Planned",
    "Scientifically-ish",
    "Almost Professional",
  ],

  batchNouns: [
    "Batch",
    "Mix",
    "Pour",
    "Blend",
    "Measure",
    "Reserve",
    "Edition",
    "Formula",
    "Craft",
    "Run",
    "Composition",
    "Creation",
    "Selection",
    "Special",
    "Series",
    "Release",
    "Assembly",
    "Combination",
    "Mixture",
    "Production",
    "Work",
    "Preparation",
    "Masterpiece",
    "Concoction",
    "Experiment",
  ],

  craftNouns: [
    "Reserve",
    "Blend",
    "Barrel",
    "Cask",
    "Cellar",
    "Foundry",
    "Forge",
    "Harbor",
    "Ember",
    "Summit",
    "Valley",
    "Meadow",
    "Workshop",
    "Estate",
    "Collection",
    "Selection",
    "Vintage",
    "Edition",
    "House",
    "Label",
    "Stock",
    "Release",
    "Series",
    "Craft",
    "Tradition",
  ],

  culinaryNouns: [
    "House Special",
    "Chef's Choice",
    "Daily Special",
    "Signature Dish",
    "Secret Sauce",
    "House Blend",
    "Kitchen Reserve",
    "Chef's Reserve",
    "Tasting Selection",
    "Artisan Recipe",
    "Seasonal Special",
    "Master Recipe",
    "Kitchen Classic",
    "Chef's Edition",
    "Fine Serving",
    "Special Preparation",
    "House Favorite",
    "Table Selection",
    "Premium Serving",
    "Recipe of the Day",
  ],

  humorousNouns: [
    "Bucket of Dreams",
    "Happy Accident",
    "Professional Guess",
    "Questionable Science",
    "Tiny Triumph",
    "Big Idea",
    "Daily Experiment",
    "Unplanned Success",
    "Bucket Situation",
    "Mixing Adventure",
    "Measured Mystery",
    "Fine Mess",
    "Bold Decision",
    "Reasonable Attempt",
    "Almost Masterpiece",
    "Unexpected Classic",
    "Suspiciously Good Batch",
    "Certified Mixture",
    "Probably a Recipe",
    "Very Serious Pour",
  ],
} as const;

export type CraftVocabulary = {
  adjectives: readonly string[];
  nouns: readonly string[];
  phrases: readonly string[];
  whimsical: readonly string[];
  exclusive: readonly string[];
  titles: readonly string[];
};

/** Craft-beer / coffee / artisan label pools — editable JSON data. */
export const CRAFT_VOCABULARY: CraftVocabulary = craftVocabularyData;

/** Professional tone — kept separate from craft JSON. */
export const PROFESSIONAL_VOCABULARY = [
  "Standard Mix",
  "Master Blend",
  "Production Batch",
  "Process Run",
  "Control Mix",
  "Reference Batch",
  "Lab Standard",
  "Work Order",
  "Line Batch",
  "QC Sample",
] as const;
