import { batchTotalsCssVarNames } from "./batchTotalsCssVars";
import { componentTokens } from "./components";
import { semanticBorders, semanticColors, semanticSurfaces } from "./semantic";

/** CSS custom property names for component tokens (injected on :root). */
export const componentCssVarNames = {
  textPrimary: "--semantic-text-primary",
  textSecondary: "--semantic-text-secondary",
  textMuted: "--semantic-text-muted",
  textDimmed: "--semantic-text-dimmed",
  textInverse: "--semantic-text-inverse",
  iconPrimary: "--semantic-icon-primary",
  iconMuted: "--semantic-icon-muted",
  stateWarn: "--semantic-state-warn",
  stateError: "--semantic-state-error",
  stateErrorMuted: "--semantic-state-error-muted",
  stateAccent: "--semantic-state-accent",
  selectionBorder: "--semantic-selection-border",
  selectionBg: "--semantic-selection-bg",
  stateDisabled: "--semantic-state-disabled",
  borderDefault: "--semantic-border-default",
  borderStrong: "--semantic-border-strong",
  borderSubtle: "--semantic-border-subtle",
  borderPanel: "--semantic-border-panel",
  borderInput: "--semantic-border-input",
  borderSheetButton: "--semantic-border-sheet-button",
  borderHeaderButton: "--semantic-border-header-button",
  borderHeaderButtonActive: "--semantic-border-header-button-active",
  surfaceRaised: "--semantic-surface-raised",
  surfaceButton: "--semantic-surface-button",
  surfaceButtonActive: "--semantic-surface-button-active",
  surfaceButtonSolid: "--semantic-surface-button-solid",
  surfaceButtonActiveSolid: "--semantic-surface-button-active-solid",
  surfaceLongPress: "--semantic-surface-long-press",
  surfaceLongPressActive: "--semantic-surface-long-press-active",
  longPressLabelIdle: "--component-long-press-label-idle",
  longPressLabelHolding: "--component-long-press-label-holding",
  longPressLabelDisabled: "--component-long-press-label-disabled",
  longPressDisabledOpacity: "--component-long-press-disabled-opacity",
  longPressProgress: "--component-long-press-progress",
  longPressBeamTrack: "--component-long-press-beam-track",
  longPressFill: "--component-long-press-fill",
  surfaceInput: "--semantic-surface-input",
  surfaceApp: "--semantic-surface-app",
  sheetPanelBorder: "--component-sheet-panel-border",
  sheetPanelBg: "--component-sheet-panel-bg",
  sheetPanelShadow: "--component-sheet-panel-shadow",
  sheetPanelOverlayLight: "--component-sheet-panel-overlay-light",
  sheetPanelOverlayMedium: "--component-sheet-panel-overlay-medium",
  sheetPanelListRowBg: "--component-sheet-panel-list-row-bg",
  sheetPanelListRowBorder: "--component-sheet-panel-list-row-border",
  sheetPanelFadeBg: "--component-sheet-panel-fade-bg",
  sheetFooterBtnBg: "--component-sheet-footer-btn-bg",
  sheetFooterBtnBorder: "--component-sheet-footer-btn-border",
  sheetFooterBtnColor: "--component-sheet-footer-btn-color",
  sheetFooterTooltipColor: "--component-sheet-footer-tooltip-color",
  sheetFooterTooltipLine: "--component-sheet-footer-tooltip-line",
  fieldInputBg: "--component-field-input-bg",
  fieldInputBorder: "--component-field-input-border",
  fieldInputBorderError: "--component-field-input-border-error",
  fieldInputColor: "--component-field-input-color",
  headerIconBtnBg: "--component-header-icon-btn-bg",
  headerIconBtnBgActive: "--component-header-icon-btn-bg-active",
  headerIconBtnBgSolid: "--component-header-icon-btn-bg-solid",
  headerIconBtnBgActiveSolid: "--component-header-icon-btn-bg-active-solid",
  headerIconBtnBorder: "--component-header-icon-btn-border",
  headerIconBtnBorderActive: "--component-header-icon-btn-border-active",
  headerIconBtnColor: "--component-header-icon-btn-color",
  headerIconBtnColorActive: "--component-header-icon-btn-color-active",
  shareIconIdleBg: "--component-share-icon-idle-bg",
  shareIconActiveBg: "--component-share-icon-active-bg",
  shareIconIdleBorder: "--component-share-icon-idle-border",
  shareIconActiveBorder: "--component-share-icon-active-border",
  shareIconIdleColor: "--component-share-icon-idle-color",
  shareIconActiveColor: "--component-share-icon-active-color",
  stripPanelBg: "--component-strip-panel-bg",
  stripNeutral: "--component-strip-neutral",
  stripMoreOpen: "--component-strip-more-open",
  stripRename: "--component-strip-rename",
  stripDelete: "--component-strip-delete",
  stripOpen: "--component-strip-open",
  stripDivider: "--component-strip-divider",
  stripDeleteColor: "--component-strip-delete-color",
  stripOpenColor: "--component-strip-open-color",
  stripRenameColor: "--component-strip-rename-color",
  stripMutedColor: "--component-strip-muted-color",
} as const;

function v(name: string): string {
  return `var(${name})`;
}

/** CSS var() references for app inline styles — override on :root for themes. */
export const cv = {
  text: {
    primary: v(componentCssVarNames.textPrimary),
    secondary: v(componentCssVarNames.textSecondary),
    muted: v(componentCssVarNames.textMuted),
    dimmed: v(componentCssVarNames.textDimmed),
    inverse: v(componentCssVarNames.textInverse),
    value: v(componentCssVarNames.textSecondary),
  },
  state: {
    warn: v(componentCssVarNames.stateWarn),
    error: v(componentCssVarNames.stateError),
    errorMuted: v(componentCssVarNames.stateErrorMuted),
    accent: v(componentCssVarNames.stateAccent),
    disabled: v(componentCssVarNames.stateDisabled),
  },
  selection: {
    border: v(componentCssVarNames.selectionBorder),
    background: v(componentCssVarNames.selectionBg),
  },
  sheetPanel: {
    border: v(componentCssVarNames.sheetPanelBorder),
    background: v(componentCssVarNames.sheetPanelBg),
    shadow: v(componentCssVarNames.sheetPanelShadow),
    overlayLight: v(componentCssVarNames.sheetPanelOverlayLight),
    overlayMedium: v(componentCssVarNames.sheetPanelOverlayMedium),
    listRowBackground: v(componentCssVarNames.sheetPanelListRowBg),
    listRowBorder: v(componentCssVarNames.sheetPanelListRowBorder),
    fadeBackground: v(componentCssVarNames.sheetPanelFadeBg),
    raisedBackground: v(componentCssVarNames.surfaceRaised),
  },
  sheetFooterButton: {
    background: v(componentCssVarNames.sheetFooterBtnBg),
    border: v(componentCssVarNames.sheetFooterBtnBorder),
    color: v(componentCssVarNames.sheetFooterBtnColor),
  },
  sheetFooterTooltip: {
    color: v(componentCssVarNames.sheetFooterTooltipColor),
    line: v(componentCssVarNames.sheetFooterTooltipLine),
  },
  headerIconButton: {
    background: v(componentCssVarNames.headerIconBtnBg),
    backgroundActive: v(componentCssVarNames.headerIconBtnBgActive),
    backgroundSolid: v(componentCssVarNames.headerIconBtnBgSolid),
    backgroundActiveSolid: v(componentCssVarNames.headerIconBtnBgActiveSolid),
    border: v(componentCssVarNames.headerIconBtnBorder),
    borderActive: v(componentCssVarNames.headerIconBtnBorderActive),
    color: v(componentCssVarNames.headerIconBtnColor),
    colorActive: v(componentCssVarNames.headerIconBtnColorActive),
  },
  fieldInput: {
    background: v(componentCssVarNames.fieldInputBg),
    border: v(componentCssVarNames.fieldInputBorder),
    borderError: v(componentCssVarNames.fieldInputBorderError),
    color: v(componentCssVarNames.fieldInputColor),
  },
  shareBar: {
    iconIdleBackground: v(componentCssVarNames.shareIconIdleBg),
    iconActiveBackground: v(componentCssVarNames.shareIconActiveBg),
    iconIdleBorder: v(componentCssVarNames.shareIconIdleBorder),
    iconActiveBorder: v(componentCssVarNames.shareIconActiveBorder),
    iconIdleColor: v(componentCssVarNames.shareIconIdleColor),
    iconActiveColor: v(componentCssVarNames.shareIconActiveColor),
    panelBorder: v(componentCssVarNames.borderPanel),
    panelBackground: v(componentCssVarNames.surfaceRaised),
    submitBackground: v(componentCssVarNames.surfaceButton),
    submitBorder: v(componentCssVarNames.borderPanel),
    submitColor: v(componentCssVarNames.textPrimary),
  },
  loadSheetStrip: {
    panelBackground: v(componentCssVarNames.stripPanelBg),
    neutral: v(componentCssVarNames.stripNeutral),
    moreOpen: v(componentCssVarNames.stripMoreOpen),
    rename: v(componentCssVarNames.stripRename),
    delete: v(componentCssVarNames.stripDelete),
    open: v(componentCssVarNames.stripOpen),
    divider: v(componentCssVarNames.stripDivider),
    deleteColor: v(componentCssVarNames.stripDeleteColor),
    openColor: v(componentCssVarNames.stripOpenColor),
    renameColor: v(componentCssVarNames.stripRenameColor),
    mutedColor: v(componentCssVarNames.stripMutedColor),
  },
  loadSheetList: {
    title: v(componentCssVarNames.textPrimary),
    muted: v(componentCssVarNames.textMuted),
    value: v(componentCssVarNames.textSecondary),
    timestamp: v(componentCssVarNames.textDimmed),
  },
  app: {
    background: v(componentCssVarNames.surfaceApp),
  },
  border: {
    default: v(componentCssVarNames.borderDefault),
    strong: v(componentCssVarNames.borderStrong),
    subtle: v(componentCssVarNames.borderSubtle),
    panel: v(componentCssVarNames.borderPanel),
    input: v(componentCssVarNames.borderInput),
  },
  surface: {
    raised: v(componentCssVarNames.surfaceRaised),
    button: v(componentCssVarNames.surfaceButton),
    buttonActive: v(componentCssVarNames.surfaceButtonActive),
    input: v(componentCssVarNames.surfaceInput),
  },
  action: {
    tapIdle: v(componentCssVarNames.surfaceButton),
    tapActive: v(componentCssVarNames.surfaceButtonActive),
    tapSolid: v(componentCssVarNames.surfaceButtonSolid),
    tapActiveSolid: v(componentCssVarNames.surfaceButtonActiveSolid),
    longPressIdle: v(componentCssVarNames.surfaceLongPress),
    longPressActive: v(componentCssVarNames.surfaceLongPressActive),
    longPressHolding: v(componentCssVarNames.surfaceInput),
  },
  longPress: {
    labelIdle: v(componentCssVarNames.longPressLabelIdle),
    labelHolding: v(componentCssVarNames.longPressLabelHolding),
    labelDisabled: v(componentCssVarNames.longPressLabelDisabled),
    disabledOpacity: v(componentCssVarNames.longPressDisabledOpacity),
    progress: v(componentCssVarNames.longPressProgress),
    beamTrack: v(componentCssVarNames.longPressBeamTrack),
    fill: v(componentCssVarNames.longPressFill),
  },
  extraBatch: {
    label: v(componentCssVarNames.textSecondary),
  },
  batchTotals: {
    tableBorder: v(componentCssVarNames.borderSubtle),
    sectionMuted: v(componentCssVarNames.textMuted),
    cardHeaderBackground: v(batchTotalsCssVarNames.cardHeaderBg),
    extraCardHeaderBackground: v(batchTotalsCssVarNames.extraCardHeaderBg),
    extraTableThBackground: v(batchTotalsCssVarNames.extraTableThBg),
    cardHeaderBtnBackground: v(componentCssVarNames.surfaceButton),
    cardHeaderBtnBorder: v(componentCssVarNames.borderHeaderButton),
    batchesCardBorder: v(componentCssVarNames.borderDefault),
    batchesCardBackground: v(batchTotalsCssVarNames.batchesCardBg),
    extraBatchBorder: v(batchTotalsCssVarNames.extraBatchBorder),
    extraBatchDashedBorder: v(batchTotalsCssVarNames.extraBatchDashedBorder),
    extraBatchBackground: v(batchTotalsCssVarNames.extraBatchBg),
    emptyCardBackground: v(batchTotalsCssVarNames.emptyCardBg),
    insetHighlight: v(batchTotalsCssVarNames.insetHighlight),
  },
} as const;

/** Flat [cssVar, value] pairs for applyWebThemeColors. */
export function getExtendedSemanticCssEntries(): [string, string][] {
  return [
    [componentCssVarNames.textPrimary, semanticColors.text.primary],
    [componentCssVarNames.textSecondary, semanticColors.text.secondary],
    [componentCssVarNames.textMuted, semanticColors.text.muted],
    [componentCssVarNames.textDimmed, semanticColors.text.dimmed],
    [componentCssVarNames.textInverse, semanticColors.text.inverse],
    [componentCssVarNames.iconPrimary, semanticColors.icon.primary],
    [componentCssVarNames.iconMuted, semanticColors.icon.muted],
    [componentCssVarNames.stateWarn, semanticColors.state.warn],
    [componentCssVarNames.stateError, semanticColors.state.error],
    [componentCssVarNames.stateErrorMuted, semanticColors.state.errorMuted],
    [componentCssVarNames.stateAccent, semanticColors.text.secondary],
    [componentCssVarNames.selectionBorder, semanticBorders.strong],
    [componentCssVarNames.selectionBg, semanticSurfaces.buttonActive],
    [componentCssVarNames.stateDisabled, semanticColors.state.disabled],
    [componentCssVarNames.borderDefault, semanticBorders.default],
    [componentCssVarNames.borderStrong, semanticBorders.strong],
    [componentCssVarNames.borderSubtle, semanticBorders.subtle],
    [componentCssVarNames.borderPanel, semanticBorders.panel],
    [componentCssVarNames.borderInput, semanticBorders.input],
    [componentCssVarNames.borderSheetButton, semanticBorders.sheetButton],
    [componentCssVarNames.borderHeaderButton, semanticBorders.headerButton],
    [componentCssVarNames.borderHeaderButtonActive, semanticBorders.headerButtonActive],
    [componentCssVarNames.surfaceRaised, semanticSurfaces.raised],
    [componentCssVarNames.surfaceButton, semanticSurfaces.button],
    [componentCssVarNames.surfaceButtonActive, semanticSurfaces.buttonActive],
    [componentCssVarNames.surfaceButtonSolid, semanticSurfaces.buttonSolid],
    [componentCssVarNames.surfaceButtonActiveSolid, semanticSurfaces.buttonActiveSolid],
    [componentCssVarNames.surfaceLongPress, semanticSurfaces.longPressAction],
    [componentCssVarNames.surfaceLongPressActive, semanticSurfaces.longPressActionActive],
    [componentCssVarNames.longPressLabelIdle, semanticColors.text.muted],
    [componentCssVarNames.longPressLabelHolding, semanticColors.text.secondary],
    [componentCssVarNames.longPressLabelDisabled, semanticColors.text.dimmed],
    [componentCssVarNames.longPressDisabledOpacity, "0.58"],
    [componentCssVarNames.longPressProgress, semanticColors.text.secondary],
    [componentCssVarNames.longPressBeamTrack, semanticSurfaces.longPressTrack],
    [componentCssVarNames.longPressFill, semanticSurfaces.longPressFill],
    [componentCssVarNames.surfaceInput, semanticSurfaces.input],
    [componentCssVarNames.surfaceApp, semanticColors.surface.app],
  ];
}

export function getComponentCssEntries(): [string, string][] {
  const t = componentTokens;
  return [
    [componentCssVarNames.sheetPanelBorder, t.sheetPanel.border],
    [componentCssVarNames.sheetPanelBg, t.sheetPanel.background],
    [componentCssVarNames.sheetPanelShadow, t.sheetPanel.shadow],
    [componentCssVarNames.sheetPanelOverlayLight, t.sheetPanel.overlayLight],
    [componentCssVarNames.sheetPanelOverlayMedium, t.sheetPanel.overlayMedium],
    [componentCssVarNames.sheetPanelListRowBg, t.sheetPanel.listRowBackground],
    [componentCssVarNames.sheetPanelListRowBorder, t.sheetPanel.listRowBorder],
    [componentCssVarNames.sheetPanelFadeBg, t.sheetPanel.fadeBackground],
    [componentCssVarNames.sheetFooterBtnBg, t.sheetFooterButton.background],
    [componentCssVarNames.sheetFooterBtnBorder, t.sheetFooterButton.border],
    [componentCssVarNames.sheetFooterBtnColor, t.sheetFooterButton.color],
    [componentCssVarNames.sheetFooterTooltipColor, t.sheetFooterTooltip.color],
    [componentCssVarNames.sheetFooterTooltipLine, t.sheetFooterTooltip.line],
    [componentCssVarNames.fieldInputBg, t.fieldInput.background],
    [componentCssVarNames.fieldInputBorder, t.fieldInput.border],
    [componentCssVarNames.fieldInputBorderError, t.fieldInput.borderError],
    [componentCssVarNames.fieldInputColor, t.fieldInput.color],
    [componentCssVarNames.headerIconBtnBg, t.headerIconButton.background],
    [componentCssVarNames.headerIconBtnBgActive, t.headerIconButton.backgroundActive],
    [componentCssVarNames.headerIconBtnBgSolid, t.headerIconButton.backgroundSolid],
    [componentCssVarNames.headerIconBtnBgActiveSolid, t.headerIconButton.backgroundActiveSolid],
    [componentCssVarNames.headerIconBtnBorder, t.headerIconButton.border],
    [componentCssVarNames.headerIconBtnBorderActive, t.headerIconButton.borderActive],
    [componentCssVarNames.headerIconBtnColor, t.headerIconButton.color],
    [componentCssVarNames.headerIconBtnColorActive, t.headerIconButton.colorActive],
    [componentCssVarNames.shareIconIdleBg, t.shareBar.iconIdleBackground],
    [componentCssVarNames.shareIconActiveBg, t.shareBar.iconActiveBackground],
    [componentCssVarNames.shareIconIdleBorder, t.shareBar.iconIdleBorder],
    [componentCssVarNames.shareIconActiveBorder, t.shareBar.iconActiveBorder],
    [componentCssVarNames.shareIconIdleColor, t.shareBar.iconIdleColor],
    [componentCssVarNames.shareIconActiveColor, t.shareBar.iconActiveColor],
    [componentCssVarNames.stripPanelBg, t.loadSheetStrip.panelBackground],
    [componentCssVarNames.stripNeutral, t.loadSheetStrip.neutral],
    [componentCssVarNames.stripMoreOpen, t.loadSheetStrip.moreOpen],
    [componentCssVarNames.stripRename, t.loadSheetStrip.rename],
    [componentCssVarNames.stripDelete, t.loadSheetStrip.delete],
    [componentCssVarNames.stripOpen, t.loadSheetStrip.open],
    [componentCssVarNames.stripDivider, t.loadSheetStrip.divider],
    [componentCssVarNames.stripDeleteColor, t.loadSheetStrip.deleteColor],
    [componentCssVarNames.stripOpenColor, t.loadSheetStrip.openColor],
    [componentCssVarNames.stripRenameColor, t.loadSheetStrip.renameColor],
    [componentCssVarNames.stripMutedColor, t.loadSheetStrip.mutedColor],
  ];
}
