import { alphaWhite } from "./primitives";
import { themeChrome } from "./chrome";
import { themeBorders } from "./borders";
import { themeSurfaces } from "./surfaces";
import { semanticBorders, semanticColors, semanticSurfaces } from "./semantic";

/**
 * Component-level tokens — the only color/border/surface API for app UI code.
 * Map semantics to UI parts; do not import theme.colors/borders/surfaces in src/app.
 */
export const componentTokens = {
  text: {
    primary: semanticColors.text.primary,
    secondary: semanticColors.text.secondary,
    muted: semanticColors.text.muted,
    dimmed: semanticColors.text.dimmed,
    dimmer: semanticColors.text.dimmed,
    inverse: semanticColors.text.inverse,
    value: semanticColors.text.secondary,
  },
  state: {
    warn: semanticColors.state.warn,
    error: semanticColors.state.error,
    errorMuted: semanticColors.state.errorMuted,
    accent: semanticColors.state.accent,
    disabled: semanticColors.state.disabled,
  },
  chrome: themeChrome,
  /** Shared idle fills — tap vs long-press families (shape/size may still differ). */
  action: {
    tapIdle: semanticSurfaces.button,
    tapActive: semanticSurfaces.buttonActive,
    tapSolid: semanticSurfaces.buttonSolid,
    tapActiveSolid: semanticSurfaces.buttonActiveSolid,
    longPressIdle: semanticSurfaces.longPressAction,
    longPressActive: semanticSurfaces.longPressActionActive,
    longPressHolding: semanticSurfaces.input,
  },
  sheetFooterButton: {
    height: 44,
    background: semanticSurfaces.button,
    border: semanticBorders.sheetButton,
    color: semanticColors.icon.primary,
    opacityDisabled: 0.45,
  },
  sheetFooterTooltip: {
    color: semanticColors.text.secondary,
    line: semanticSurfaces.tooltipLine,
  },
  headerIconButton: {
    background: semanticSurfaces.headerButton,
    backgroundActive: semanticSurfaces.headerButtonActive,
    backgroundSolid: semanticSurfaces.headerButtonSolid,
    backgroundActiveSolid: semanticSurfaces.headerButtonActiveSolid,
    border: semanticBorders.headerButton,
    borderActive: semanticBorders.headerButtonActive,
    color: semanticColors.icon.muted,
    colorActive: semanticColors.icon.primary,
    opacityDisabled: 0.4,
  },
  /** Text/icon only — no fill or border chrome. */
  textButton: {
    background: semanticSurfaces.transparent,
    border: "none",
    color: semanticColors.text.secondary,
    colorActive: semanticColors.text.primary,
    opacityDisabled: 0.4,
  },
  fieldInput: {
    background: semanticSurfaces.input,
    border: semanticBorders.input,
    borderError: `1.5px solid ${semanticColors.state.error}`,
    color: semanticColors.text.primary,
  },
  sheetPanel: {
    border: semanticBorders.panel,
    background: semanticSurfaces.loadSheetPanel,
    shadow: themeSurfaces.shadowSheet,
    overlayLight: semanticSurfaces.outsideDimLight,
    overlayMedium: semanticSurfaces.outsideDimMedium,
    listRowBackground: semanticSurfaces.loadSheetRow,
    listRowBorder: semanticBorders.panel,
    fadeBackground: semanticSurfaces.loadSheetPanel,
    raisedBackground: semanticColors.surface.raised,
  },
  loadSheetStrip: {
    panelBackground: semanticSurfaces.buttonSolid,
    neutral: semanticSurfaces.buttonSolid,
    moreOpen: semanticSurfaces.buttonActiveSolid,
    rename: semanticSurfaces.buttonSolid,
    delete: semanticSurfaces.buttonSolid,
    open: semanticSurfaces.buttonSolid,
    divider: semanticBorders.default,
    deleteColor: semanticColors.state.error,
    openColor: semanticColors.text.secondary,
    renameColor: semanticColors.text.primary,
    mutedColor: semanticColors.text.muted,
  },
  loadSheetList: {
    title: semanticColors.text.primary,
    muted: semanticColors.text.muted,
    value: semanticColors.text.secondary,
    timestamp: semanticColors.text.dimmed,
  },
  longPress: {
    progress: semanticColors.text.secondary,
    beamTrack: semanticSurfaces.longPressTrack,
    fill: semanticSurfaces.longPressFill,
    labelPrimary: semanticColors.text.muted,
    labelSecondary: semanticColors.icon.muted,
    labelCompact: semanticColors.text.muted,
    labelDisabled: semanticColors.state.disabled,
    labelHolding: semanticColors.text.secondary,
    labelHoldingHeader: semanticColors.text.primary,
    labelHeaderIdle: semanticColors.text.muted,
    surfaceHeaderIdle: semanticSurfaces.headerButton,
    surfaceHeaderActive: semanticSurfaces.headerButtonActive,
    surfaceSheetIdle: semanticSurfaces.button,
    surfaceSheetActive: semanticSurfaces.buttonActive,
    surfaceRaised: semanticColors.surface.raised,
    surfaceHolding: semanticColors.surface.input,
    opacityDisabledHeader: 0.35,
    opacityDisabledSheet: 0.58,
    borderWidthHeader: 1,
    borderWidthSheet: 1.5,
    borderAlpha: {
      disabled: 0.07,
      headerIdle: 0.07,
      primaryIdle: 0.12,
      secondaryIdle: 0.1,
      holdingHeader: 0.28,
      holdingSheet: 0.14,
      litHeader: 0.28,
      litSheet: 0.22,
    },
  },
  shareBar: {
    iconIdleBackground: semanticSurfaces.button,
    iconActiveBackground: semanticSurfaces.button,
    iconIdleBorder: semanticBorders.default,
    iconActiveBorder: semanticBorders.strong,
    iconIdleColor: semanticColors.text.muted,
    iconActiveColor: semanticColors.text.secondary,
    panelBorder: semanticBorders.panel,
    panelBackground: semanticColors.surface.raised,
    submitBackground: semanticSurfaces.button,
    submitBorder: semanticBorders.panel,
    submitColor: semanticColors.text.primary,
    tabGroupBackground: semanticSurfaces.actionIdle,
    doneHeight: 44,
  },
  batchTotals: {
    tableBorder: semanticBorders.subtle,
    sectionMuted: semanticColors.text.muted,
    thMuted: semanticColors.text.muted,
    cardHeaderBackground: semanticSurfaces.cardHeader,
    extraCardHeaderBackground: themeSurfaces.extraCardHeaderBg,
    extraTableThBackground: themeSurfaces.extraTableThBg,
    cardHeaderBtnBackground: semanticSurfaces.button,
    cardHeaderBtnBorder: semanticBorders.headerButton,
    cardRoundBtnDisabledOpacity: 0.35,
    batchesCardBorder: semanticBorders.default,
    batchesCardBackground: semanticSurfaces.batchesCard,
    extraBatchBorder: themeBorders.extraBatch,
    extraBatchDashedBorder: themeBorders.extraBatchDashed,
    extraBatchBackground: semanticSurfaces.extraBatch,
    emptyCardBackground: semanticSurfaces.emptyCard,
    insetHighlight: themeSurfaces.insetHighlight,
    sheetDockBackground: semanticSurfaces.sheetDock,
    sheetBodyBackground: semanticSurfaces.sheetBody,
  },
  dropdown: {
    menuBackground: semanticColors.surface.dropdown,
    menuBorderColor: themeSurfaces.dropdownMenuBorderColor,
    menuBorder: `1px solid ${themeSurfaces.dropdownMenuBorderColor}`,
    menuShadow: themeSurfaces.shadowDropdown,
    menuText: semanticColors.text.secondary,
    menuTextMuted: semanticColors.text.dimmed,
    menuLockedLabel: semanticColors.text.muted,
    menuActiveBackground: semanticSurfaces.dropdownActive,
    menuHoldingText: semanticColors.text.primary,
    inputSurface: semanticColors.surface.input,
    searchBackground: semanticSurfaces.search,
    searchBorder: semanticBorders.search,
  },
  recipeMeta: {
    id: semanticColors.text.muted,
    idMuted: semanticColors.text.dimmed,
    value: semanticColors.text.secondary,
    valueMuted: semanticColors.text.muted,
    unit: semanticColors.text.muted,
    colon: semanticColors.text.dimmed,
  },
  bucket: {
    fill: semanticColors.text.secondary,
    fillMuted: semanticColors.text.dimmed,
    fillFull: semanticColors.state.error,
    fillFullMuted: semanticColors.state.errorMuted,
    fillOutline: alphaWhite(0.36),
    fillEmpty: semanticSurfaces.bucketFillEmpty,
  },
  entityCard: {
    valueInactive: semanticColors.text.secondary,
    unitInactive: semanticColors.text.muted,
    surfaceIdle: semanticColors.surface.raised,
    borderIdle: alphaWhite(0.22),
    transition: themeChrome.cardChromeTransition,
  },
  featureReadout: {
    panelBackground: semanticSurfaces.transparent,
    panelBorder: semanticBorders.panel,
    title: semanticColors.text.muted,
    titleMuted: semanticColors.text.dimmed,
    value: semanticColors.text.secondary,
    valueMuted: semanticColors.text.muted,
  },
  mixerSwipe: {
    arrowIdle: semanticColors.text.muted,
    stepIdle: semanticColors.text.dimmed,
    surfaceBase: semanticColors.surface.swipe,
    limitColor: semanticColors.state.error,
    stripeInverse: semanticColors.text.inverse,
    columnBorder: `1px solid ${alphaWhite(0.08)}`,
    overlayHint: semanticSurfaces.overlayHint,
    recipeRatioBackground: semanticSurfaces.transparent,
  },
  app: {
    background: semanticColors.surface.app,
  },
  lockedAction: {
    primaryBorder: semanticBorders.strong,
  },
  extraBatch: {
    label: semanticColors.text.secondary,
  },
} as const;
