import { semanticSurfaces } from "./semantic";

/** Semi-transparent fills, overlays, and shadows — alias semantic tokens. */
export const themeSurfaces = {
  transparent: semanticSurfaces.transparent,
  batchesCardBg: semanticSurfaces.batchesCard,
  cardHeaderBg: semanticSurfaces.cardHeader,
  tableThBg: semanticSurfaces.cardHeader,
  extraBatchBg: semanticSurfaces.extraBatch,
  extraCardHeaderBg: "rgba(155, 140, 255, 0.14)",
  extraTableThBg: "rgba(155, 140, 255, 0.18)",
  emptyCardBg: semanticSurfaces.emptyCard,
  headerBtnBg: semanticSurfaces.headerButton,
  headerBtnBgActive: semanticSurfaces.headerButtonActive,
  headerSubBg: semanticSurfaces.headerSub,
  cardHeaderBtnBg: semanticSurfaces.headerButton,
  shareTabGroupBg: semanticSurfaces.actionIdle,
  shareTabActiveBg: semanticSurfaces.button,
  shareInputBg: semanticSurfaces.inputSubtle,
  shareSubmitBg: semanticSurfaces.button,
  dropdownMenuActiveBg: semanticSurfaces.dropdownActive,
  dropdownMenuBorderColor: "rgba(255,255,255,0.2)",
  bucketFillEmpty: semanticSurfaces.bucketFillEmpty,
  longPressTrack: semanticSurfaces.longPressTrack,
  longPressBeamTrack: semanticSurfaces.longPressTrack,
  longPressFill: semanticSurfaces.longPressFill,
  longPressFillActive: semanticSurfaces.longPressFillActive,
  actionBgIdle: semanticSurfaces.actionIdle,
  actionBgActive: semanticSurfaces.actionActive,
  actionBorderIdle: "rgba(255,255,255,0.16)",
  sheetPanel: semanticSurfaces.sheetPanelSolid,
  sheetPanelFade: "rgba(13, 13, 28, 0.9)",
  loadSheetRow: semanticSurfaces.loadSheetRow,
  loadSheetPanel: semanticSurfaces.loadSheetPanel,
  sheetPanelBlur: "20px",
  sheetPanelSaturate: 1.1,
  outsideDimLight: semanticSurfaces.outsideDimLight,
  outsideDimMedium: semanticSurfaces.outsideDimMedium,
  outsideDimBlur: "12px",
  outsideDimSaturate: 1.08,
  overlayHint: semanticSurfaces.overlayHint,
  searchBg: semanticSurfaces.search,
  inputBg: semanticSurfaces.input,
  sheetBtnBg: semanticSurfaces.button,
  sheetBtnBgActive: semanticSurfaces.buttonActive,
  sheetCancelBg: semanticSurfaces.button,
  mixerInputSecondaryBg: semanticSurfaces.button,
  mixerInputPrimaryBg: semanticSurfaces.buttonActive,
  shadowDropdown: "0 8px 20px rgba(0,0,0,0.4)",
  shadowSheet: "0 20px 56px rgba(0, 0, 0, 0.32)",
  shadowMixerInputSheet:
    "0 -8px 48px rgba(0, 0, 0, 0.45), 0 20px 56px rgba(0, 0, 0, 0.32)",
  insetHighlight: "inset 0 1px 0 rgba(255,255,255,0.08)",
  insetHighlightSubtle: "inset 0 1px 0 rgba(255,255,255,0.1)",
} as const;
