/**
 * Runtime appearance palettes — edit colors here for light + high-contrast modes.
 *
 * | Appearance        | Edit here              | Also affects compile-time tokens |
 * |-------------------|------------------------|----------------------------------|
 * | Dark + default    | semantic.ts, borders.ts, surfaces.ts | yes (componentTokens) |
 * | Dark + high       | darkHighContrastPalette below        | no  |
 * | Light + default   | lightDefaultPalette below            | no  |
 * | Light + high      | lightHighContrastPalette below       | no  |
 */
import {
  alphaBlack,
  alphaWhite,
  borderSolid,
  borderSolidBlack,
  primitiveInk,
  primitiveInkText,
  primitivePaper,
  primitiveSemanticLight,
} from "./primitives";
import type { ThemePalette } from "./themePaletteTypes";

const ink = primitiveInkText;
const paper = primitivePaper;
const sem = primitiveSemanticLight;

/** Light + default — `data-theme="light"`. */
export const lightDefaultPalette: ThemePalette = {
  text: {
    primary: ink[80],
    secondary: ink[60],
    muted: ink[50],
    dimmed: ink[20],
    inverse: ink[100],
  },
  state: {
    warn: sem.warn,
    error: sem.error,
    errorMuted: sem.errorMuted,
    disabled: ink[10],
  },
  borders: {
    subtle: borderSolidBlack(0.08),
    default: borderSolidBlack(0.12, "1.5px"),
    strong: borderSolidBlack(0.18, "1.5px"),
    panel: borderSolidBlack(0.14, "1.5px"),
    input: borderSolidBlack(0.14),
    sheetButton: borderSolidBlack(0.14, "1.5px"),
    headerButton: borderSolidBlack(0.08),
    headerButtonActive: borderSolidBlack(0.16),
  },
  surfaces: {
    raised: paper[650],
    button: alphaBlack(0.06),
    buttonActive: alphaBlack(0.1),
    buttonSolid: "#e6e6ec",
    buttonActiveSolid: "#dedee6",
    input: paper[800],
    inputSolid: paper[700],
    headerButton: alphaBlack(0.05),
    headerButtonActive: alphaBlack(0.08),
    headerButtonSolid: "#e2e2ea",
    headerButtonActiveSolid: "#d8d8e2",
    app: paper[900],
    shell: paper[950],
    header: paper[850],
    headerSub: paper[800],
    loadSheetPanel: "rgba(244, 244, 248, 0.88)",
    loadSheetRow: "rgba(244, 244, 248, 0.94)",
    outsideDimLight: "rgba(0, 0, 0, 0.18)",
    outsideDimMedium: "rgba(0, 0, 0, 0.28)",
    tooltipLine: alphaBlack(0.16),
    dropdown: paper[700],
    swipe: paper[800],
    longPressAction: "#c4c4cc",
    longPressActionActive: "#b4b4bc",
    longPressLabelIdle: ink[60],
    longPressLabelHolding: ink[80],
    longPressLabelDisabled: ink[50],
    longPressDisabledOpacity: "0.58",
    longPressProgress: ink[60],
    longPressBeamTrack: alphaBlack(0.12),
    longPressFill: alphaBlack(0.06),
  },
  legacy: {
    entityBorderIdle: alphaBlack(0.14),
    fillOutline: alphaBlack(0.2),
    fillEmpty: alphaBlack(0.04),
    actionDisabledLabel: ink[10],
  },
  chrome: {
    headerBorder: borderSolidBlack(0.08),
    headerSubBg: paper[800],
    headerSubInset: "inset 0 1px 0 rgba(0, 0, 0, 0.06)",
    outsideDimBlur: "12px",
    outsideDimSaturate: "1.02",
    sheetPanelBlur: "20px",
    sheetPanelSaturate: "1.02",
    sheetPanelShadow: "0 20px 56px rgba(0, 0, 0, 0.12)",
  },
  shareIconIdleUsesRaised: true,
};

/** Dark + high — `data-theme="dark"` + `data-contrast="high"`. */
export const darkHighContrastPalette: ThemePalette = {
  text: {
    primary: "#ffffff",
    secondary: "#f0f0fa",
    muted: "#d4d4ec",
    dimmed: "#b0b0cc",
    inverse: "#ffffff",
  },
  state: {
    warn: "#f4d898",
    error: "#ff8a9a",
    errorMuted: "#d07080",
    disabled: "#9090b0",
  },
  borders: {
    subtle: borderSolid(0.28),
    default: borderSolid(0.36, "1.5px"),
    strong: borderSolid(0.44, "1.5px"),
    panel: borderSolid(0.38, "1.5px"),
    input: borderSolid(0.32),
    sheetButton: borderSolid(0.36, "1.5px"),
    headerButton: borderSolid(0.28),
    headerButtonActive: borderSolid(0.4),
  },
  surfaces: {
    raised: "#1e1e3c",
    button: alphaWhite(0.18),
    buttonActive: alphaWhite(0.24),
    buttonSolid: "#42424e",
    buttonActiveSolid: "#4c4c58",
    input: alphaWhite(0.14),
    inputSolid: "#161632",
    headerButton: alphaWhite(0.12),
    headerButtonActive: alphaWhite(0.2),
    headerButtonSolid: "#2a2a36",
    headerButtonActiveSolid: "#363642",
    app: primitiveInk[900],
    shell: primitiveInk[950],
    header: primitiveInk[850],
    headerSub: primitiveInk[800],
    loadSheetPanel: "rgba(10, 10, 24, 0.82)",
    loadSheetRow: "rgba(10, 10, 24, 0.88)",
    outsideDimLight: "rgba(3, 3, 12, 0.48)",
    outsideDimMedium: "rgba(3, 3, 12, 0.62)",
    tooltipLine: alphaWhite(0.44),
    dropdown: "#444460",
    swipe: "#101028",
    longPressAction: "#44444e",
    longPressActionActive: "#50505a",
    longPressLabelIdle: "#ffffff",
    longPressLabelHolding: "#ffffff",
    longPressLabelDisabled: "#d4d4ec",
    longPressDisabledOpacity: "0.68",
    longPressProgress: "#f0f0fa",
    longPressBeamTrack: alphaWhite(0.18),
    longPressFill: alphaWhite(0.1),
  },
  legacy: {
    entityBorderIdle: alphaWhite(0.36),
    fillOutline: alphaWhite(0.48),
    fillEmpty: alphaWhite(0.06),
    actionDisabledLabel: "#9090b0",
  },
  chrome: {
    headerBorder: borderSolid(0.24),
    headerSubInset: "inset 0 1px 0 rgba(255, 255, 255, 0.08)",
    sheetPanelShadow: "0 20px 56px rgba(0, 0, 0, 0.48)",
  },
  shareIconIdleUsesRaised: false,
};

/** Light + high — `data-theme="light"` + `data-contrast="high"`. */
export const lightHighContrastPalette: ThemePalette = {
  text: {
    primary: ink[90],
    secondary: ink[70],
    muted: ink[60],
    dimmed: ink[40],
    inverse: ink[100],
  },
  state: {
    warn: "#6a5018",
    error: "#901828",
    errorMuted: "#702030",
    disabled: ink[30],
  },
  borders: {
    subtle: borderSolidBlack(0.16),
    default: borderSolidBlack(0.24, "1.5px"),
    strong: borderSolidBlack(0.34, "1.5px"),
    panel: borderSolidBlack(0.26, "1.5px"),
    input: borderSolidBlack(0.2),
    sheetButton: borderSolidBlack(0.26, "1.5px"),
    headerButton: borderSolidBlack(0.14),
    headerButtonActive: borderSolidBlack(0.24),
  },
  surfaces: {
    raised: paper[600],
    button: alphaBlack(0.1),
    buttonActive: alphaBlack(0.14),
    buttonSolid: "#dedee4",
    buttonActiveSolid: "#d4d4dc",
    input: paper[750],
    inputSolid: paper[700],
    headerButton: alphaBlack(0.07),
    headerButtonActive: alphaBlack(0.11),
    headerButtonSolid: "#e0e0e8",
    headerButtonActiveSolid: "#d6d6e0",
    app: paper[900],
    shell: paper[950],
    header: paper[850],
    headerSub: paper[800],
    loadSheetPanel: "rgba(250, 250, 252, 0.94)",
    loadSheetRow: "rgba(250, 250, 252, 0.98)",
    outsideDimLight: "rgba(0, 0, 0, 0.28)",
    outsideDimMedium: "rgba(0, 0, 0, 0.4)",
    tooltipLine: alphaBlack(0.24),
    dropdown: paper[650],
    swipe: paper[750],
    longPressAction: alphaBlack(0.14),
    longPressActionActive: alphaBlack(0.18),
    longPressLabelIdle: ink[90],
    longPressLabelHolding: ink[90],
    longPressLabelDisabled: ink[60],
    longPressDisabledOpacity: "0.72",
    longPressProgress: ink[70],
    longPressBeamTrack: alphaBlack(0.16),
    longPressFill: alphaBlack(0.08),
  },
  legacy: {
    entityBorderIdle: alphaBlack(0.24),
    fillOutline: alphaBlack(0.32),
    fillEmpty: alphaBlack(0.05),
    actionDisabledLabel: ink[30],
  },
  chrome: {
    headerBorder: borderSolidBlack(0.16),
    headerSubBg: paper[800],
    headerSubInset: "inset 0 1px 0 rgba(0, 0, 0, 0.1)",
    outsideDimBlur: "12px",
    outsideDimSaturate: "1.04",
    sheetPanelBlur: "20px",
    sheetPanelSaturate: "1.04",
    sheetPanelShadow: "0 20px 56px rgba(0, 0, 0, 0.18)",
  },
  shareIconIdleUsesRaised: false,
};
